---
- name: AMI Test Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy the EC2 instance
      block:
        - name: Find the EC2 instance
          amazon.aws.ec2_instance_info:
            region: "{{ region }}"
            filters:
              tag:Name: "{{ name_prefix }}"
          register: ec2_info
        - name: Destroy the EC2 instance
          amazon.aws.ec2_instance:
            state: absent
            region: "{{ region }}"
            instance_ids: "{{ item.instance_id }}"
          when: ec2_info.instances | length > 0
          loop: "{{ ec2_info.instances }}"
          loop_control:
            label: "{{ item.instance_id }}"

    - name: Destroy the SSH key pair
      amazon.aws.ec2_key:
        name: "{{ name_prefix }}-admin"
        state: absent

    - name: Destroy the security group
      amazon.aws.ec2_security_group:
        name: "{{ name_prefix }}"
        state: absent

    - name: Destroy the VPC
      block:
        - name: Find the VPC
          amazon.aws.ec2_vpc_net_info:
            region: "{{ region }}"
            filters:
              tag:Name: "{{ name_prefix }}"
          register: vpc_info

        - name: Destroy the VPC
          when: vpc_info.vpcs | length > 0
          block:
            - name: Set the VPC ID
              ansible.builtin.set_fact:
                vpc_id: "{{ vpc_info.vpcs[0].id }}"

            - name: Destroy the Route Tables
              block:
                - name: Find the Route Tables
                  amazon.aws.ec2_vpc_route_table_info:
                    region: "{{ region }}"
                    filters:
                      vpc-id: "{{ vpc_id }}"
                      association.main: "false" # NB skip because the main route tables cannot be destroyed.
                  register: rt_info

                - name: Destroy the Route Tables
                  amazon.aws.ec2_vpc_route_table:
                    state: absent
                    region: "{{ region }}"
                    vpc_id: "{{ vpc_id }}"
                    route_table_id: "{{ item.route_table_id }}"
                    lookup: id
                  when: rt_info.route_tables | length > 0
                  loop: "{{ rt_info.route_tables }}"
                  loop_control:
                    label: "{{ item.route_table_id }}"

            - name: Destroy the Internet Gateway
              block:
                - name: Find Internet Gateways
                  amazon.aws.ec2_vpc_igw_info:
                    region: "{{ region }}"
                    filters:
                      attachment.vpc-id: "{{ vpc_id }}"
                  register: igw_info

                - name: Destroy Internet Gateway
                  amazon.aws.ec2_vpc_igw:
                    state: absent
                    internet_gateway_id: "{{ item.internet_gateway_id }}"
                    vpc_id: "{{ vpc_id }}"
                  when: igw_info.internet_gateways | length > 0
                  loop: "{{ igw_info.internet_gateways }}"
                  loop_control:
                    label: "{{ item.internet_gateway_id }}"

            - name: Destroy the subnets
              block:
                - name: Find the subnets
                  amazon.aws.ec2_vpc_subnet_info:
                    region: "{{ region }}"
                    filters:
                      vpc-id: "{{ vpc_id }}"
                  register: subnet_info

                - name: Destroy the subnets
                  amazon.aws.ec2_vpc_subnet:
                    state: absent
                    vpc_id: "{{ vpc_id }}"
                    cidr: "{{ item.cidr_block }}"
                  loop: "{{ subnet_info.subnets }}"
                  loop_control:
                    label: "{{ item.subnet_id }}"

            - name: Destroy the VPC
              amazon.aws.ec2_vpc_net:
                state: absent
                vpc_id: "{{ vpc_id }}"
